{% set data=load_setup_py_data() %}

package:
  name: versionpy
  version: {{ data.version }}

source:
  path: ../../

build:
  number: 0

requirements:
  build:
    - python >=3.7
    {% for dep in data.install_requires -%}
    - {{ dep.lower() }}
    {% endfor %}
  run:
    - python >=3.7
    {% for dep in data.install_requires -%}
    - {{ dep.lower() }}
    {% endfor %}

test:
  imports:
    - versionpy
  commands:
    - bump --help

about:
  home: "{{ data.url }}"
  license: "GNU General Public License v3 (GPLv3)"
  license_family: GPL3
  summary: "{{ data.description }}"
